export * from './Splash/Splash'
export * from './SignIn/SignIn'
export * from './Onboarding/Onboarding'
export * from './SignUp/SignUp'
export * from './Home/Home'
export * from './Calls/Calls'
export * from './Contacts/Contacts'
export * from './Settings/Settings'